source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'FBNetworkErrorLogger_Tests', :exclusive => true do
  pod "FBNetworkErrorLogger", :path => "../"

  pod 'Kiwi'
  pod 'OHHTTPStubs'
end
